In [9]:
import pandas as pd
Data = pd.read_csv('../data/SCMS_Delivery_History_Dataset_20150929 (2).csv', encoding="ISO-8859-1")
Data.head()

,ID,Project Code,PQ #,PO / SO #,ASN/DN #,Country,Managed By,Fulfill Via,Vendor INCO Term,Shipment Mode,...,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,Unit Price,Manufacturing Site,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD)
0,1,100-CI-T01,Pre-PQ Process,SCMS-4,ASN-8,Côte d'Ivoire,PMO - US,Direct Drop,EXW,Air,...,30,19,551.0,29.00,0.97,Ranbaxy Fine Chemicals LTD,Yes,13,780.34,NaN
1,3,108-VN-T01,Pre-PQ Process,SCMS-13,ASN-85,Vietnam,PMO - US,Direct Drop,EXW,Air,...,240,1000,6200.0,6.20,0.03,"Aurobindo Unit III, India",Yes,358,4521.5,NaN
2,4,100-CI-T01,Pre-PQ Process,SCMS-20,ASN-14,Côte d'Ivoire,PMO - US,Direct Drop,FCA,Air,...,100,500,40000.0,80.00,0.80,ABBVIE GmbH & Co.KG Wiesbaden,Yes,171,1653.78,NaN
3,15,108-VN-T01,Pre-PQ Process,SCMS-78,ASN-50,Vietnam,PMO - US,Direct Drop,EXW,Air,...,60,31920,127360.8,3.99,0.07,"Ranbaxy, Paonta Shahib, India",Yes,1855,16007.06,NaN
4,16,108-VN-T01,Pre-PQ Process,SCMS-81,ASN-55,Vietnam,PMO - US,Direct Drop,EXW,Air,...,60,38000,121600.0,3.20,0.05,"Aurobindo Unit III, India",Yes,7590,45450.08,NaN

In [ ]:
col = Data["Line Item Value"]
df_selected2.insert(loc=9, column='Line Item Value', value=col)
import pandas as pd


colonnes_selectionnees = [
    'Line Item Value',
         
]

df_selected = Data[colonnes_selectionnees]

df_selected.head()

   Line Item Value
0            551.0
1           6200.0
2          40000.0
3         127360.8
4         121600.0

In [14]:
df = pd.read_csv('../data/SCMS_Delivery_History_Dataset1.csv', encoding="ISO-8859-1")
df.head()

,Line Item Quantity,Weight (Kilograms),Freight Cost (USD),Delayed,Processing Time (Days),Fulfill Via_Direct Drop,Shipment Mode_Air,Shipment Mode_Air Charter,Shipment Mode_Ocean,Shipment Mode_Truck,...,Country_Zimbabwe,Product Group_ACT,Product Group_ANTM,Product Group_ARV,Product Group_MRDT,Delivery Quarter_1,Delivery Quarter_2,Delivery Quarter_3,Delivery Quarter_4,Vendor_encoded
0,19,13.0,780.34,0,24.0,True,True,False,False,False,...,False,False,False,False,False,False,True,False,False,2
1,1000,358.0,4521.50,0,24.0,True,True,False,False,False,...,False,False,False,True,False,False,False,False,True,668
2,500,171.0,1653.78,0,24.0,True,True,False,False,False,...,False,False,False,False,False,False,False,True,False,21
3,31920,1855.0,16007.06,0,24.0,True,True,False,False,False,...,False,False,False,True,False,False,False,True,False,9
4,38000,7590.0,45450.08,0,24.0,True,True,False,False,False,...,False,False,False,True,False,False,False,True,False,668

In [42]:
import pandas as pd


colonnes_selectionnees2 = [
    'Weight (Kilograms)',
    'Freight Cost (USD)',
    'Processing Time (Days)',
    'Shipment Mode_Truck',
    'Country_Congo, DRC',
    'Country_CÃ´te d\'Ivoire',
    'Country_Mozambique',
    'Country_Uganda',
    'Country_Zambia',
    'Delivery Quarter_1',
    'Delivery Quarter_2',
    'Delivery Quarter_3',
    'Delivery Quarter_4',
    'Vendor_encoded',
    'Delayed'




]

df_selected2 = df[colonnes_selectionnees2]

df_selected2.head()

,Weight (Kilograms),Freight Cost (USD),Processing Time (Days),Shipment Mode_Truck,"Country_Congo, DRC",Country_CÃ´te d'Ivoire,Country_Mozambique,Country_Uganda,Country_Zambia,Delivery Quarter_1,Delivery Quarter_2,Delivery Quarter_3,Delivery Quarter_4,Vendor_encoded,Delayed
0,13.0,780.34,24.0,False,False,True,False,False,False,False,True,False,False,2,0
1,358.0,4521.50,24.0,False,False,False,False,False,False,False,False,False,True,668,0
2,171.0,1653.78,24.0,False,False,True,False,False,False,False,False,True,False,21,0
3,1855.0,16007.06,24.0,False,False,False,False,False,False,False,False,True,False,9,0
4,7590.0,45450.08,24.0,False,False,False,False,False,False,False,False,True,False,668,0

In [45]:
col = Data["Line Item Value"]
df_selected2.drop(columns=['Line Item Value'], inplace=True)
df_selected2.insert(loc=0, column='Line Item Value', value=col)

C:\Users\asus\AppData\Local\Temp\ipykernel_66876\4122052849.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected2.drop(columns=['Line Item Value'], inplace=True)

In [46]:
df_selected2.head()

,Line Item Value,Weight (Kilograms),Freight Cost (USD),Processing Time (Days),Shipment Mode_Truck,"Country_Congo, DRC",Country_CÃ´te d'Ivoire,Country_Mozambique,Country_Uganda,Country_Zambia,Delivery Quarter_1,Delivery Quarter_2,Delivery Quarter_3,Delivery Quarter_4,Vendor_encoded,Delayed
0,551.0,13.0,780.34,24.0,False,False,True,False,False,False,False,True,False,False,2,0
1,6200.0,358.0,4521.50,24.0,False,False,False,False,False,False,False,False,False,True,668,0
2,40000.0,171.0,1653.78,24.0,False,False,True,False,False,False,False,False,True,False,21,0
3,127360.8,1855.0,16007.06,24.0,False,False,False,False,False,False,False,False,True,False,9,0
4,121600.0,7590.0,45450.08,24.0,False,False,False,False,False,False,False,False,True,False,668,0

In [47]:
df_selected2.to_csv('../data/SCMS_selected_features.csv', index=False)